
/*
 * To use basil tool:
 *
 * 1. From the compiler window, select the gear icon and choose "Link to binary"
 * 2. From the compiler window, select "Add tool" and choose a tool.
 *
 *      - BASIL (.bpl output): output the generated boogie file
 *      - BASIL (IL output): output the Basil IL
 *      - BASIL (Boogie verifier): run the boogie tool on the file generated by BASIL
 *      - readelf (aarch64): The output of `aarch64-linux-gnu-readelf`
 *
 *  To add spec files or pass custom arguments to BASIL, use the multi-file tree view:
 *
 *  1. Click Templates in the top bar.
 *  2. Choose a BASIL example to set up the layout.
 *
 *
 *  To run a boogie file directly:
 *
 *  1. From the dropdown change "C" to "Boogie IVL"
 *  2. In the source editor select "Add new" and choose compiler
 *
 */

/* Type your code here, or load an example. */
int square(int num) {
    return num * num;
}
