compilers=&boogie
defaultCompiler=boogie


group.boogie.compilerType=boogie
group.boogie.compilers=boogie
group.boogie.isSemVer=false
group.boogie.baseName=boogie
group.boogie.groupName=boogie

compiler.boogie.exe=basil-task
compiler.boogie.options=boogie-only

supportsBinary=false
interpreted=true
objdumper=
demangler=
postProcess=
options=
supportsExecute=false
stubText=
