# Default settings for C
compilers=&gcc:&clang:&aarch64
defaultCompiler=gccaarch
demangler=c++filt
objdumper=objdump
postProcess=
supportsBinary=true
supportsBinaryObject=true
binaryHideFuncRe=^(__.*|_(init|start|fini)|(de)?register_tm_clones|call_gmon_start|frame_dummy|\.plt.*)$
stubRe=\bmain\b
stubText=int main(void){return 0;/*stub provided by Compiler Explorer*/}
supportsLibraryCodeFilter=true

group.aarch64.compilers=gccaarch:clangaarch
group.aarch64.groupName=AArch64 compilers for Basil

compiler.gccaarch.exe=aarch64-unknown-linux-gnu-gcc
compiler.gccaarch.name=gcc (aarch64)
compiler.gccaarch.objdumper=aarch64-unknown-linux-gnu-objdump
compiler.gccaarch.supportsBinaryObject=true

compiler.clangaarch.exe=aarch64-unknown-linux-gnu-clang
compiler.clangaarch.objdumper=aarch64-unknown-linux-gnu-objdump
compiler.clangaarch.name=clang (aarch64)
compiler.clangaarch.supportsBinaryObject=true
# compiler.clangaarch.options=--target=aarch64-linux-gnu

group.gcc.compilers=cg44:cg45:cg46:cg47:cg48:cg5:cg6x:cg7:cg8:cg9:cg10:cg11:cgdefault
compiler.cg44.exe=/usr/bin/gcc-4.4
compiler.cg44.name=gcc 4.4
compiler.cg45.exe=/usr/bin/gcc-4.5
compiler.cg45.name=gcc 4.5
compiler.cg46.exe=/usr/bin/gcc-4.6
compiler.cg46.name=gcc 4.6
compiler.cg47.exe=/usr/bin/gcc-4.7
compiler.cg47.name=gcc 4.7
compiler.cg48.exe=/usr/bin/gcc-4.8
compiler.cg48.name=gcc 4.8
compiler.cg5.exe=/usr/bin/gcc-5
compiler.cg5.name=gcc 5.x
compiler.cg6x.exe=/usr/bin/gcc-6
compiler.cg6x.name=gcc 6.x
compiler.cg6x.alias=cg6
compiler.cg7.exe=/usr/bin/gcc-7
compiler.cg7.name=gcc 7.x
compiler.cg8.exe=/usr/bin/gcc-8
compiler.cg8.name=gcc 8.x
compiler.cg9.exe=/usr/bin/gcc-9
compiler.cg9.name=gcc 9.x
compiler.cg10.exe=/usr/bin/gcc-10
compiler.cg10.name=gcc 10.x
compiler.cg11.exe=/usr/bin/gcc-11
compiler.cg11.name=gcc 11.x
compiler.cgdefault.exe=/usr/bin/gcc
compiler.cgdefault.name=gcc default

group.clang.compilers=cclang7:cclang8:cclang9:cclang10:cclang11:cclang12:cclangdefault:cclangccdefault
group.clang.intelAsm=-mllvm --x86-asm-syntax=intel
compiler.cclang7.exe=/usr/bin/clang-7
compiler.cclang7.name=clang 7
compiler.cclang8.exe=/usr/bin/clang-8
compiler.cclang8.name=clang 8
compiler.cclang9.exe=/usr/bin/clang-9
compiler.cclang9.name=clang 9
compiler.cclang10.exe=/usr/bin/clang-10
compiler.cclang10.name=clang 10
compiler.cclang11.exe=/usr/bin/clang-11
compiler.cclang11.name=clang 11
compiler.cclang12.exe=/usr/bin/clang-12
compiler.cclang12.name=clang 12
compiler.cclangdefault.exe=/usr/bin/clang
compiler.cclangdefault.name=clang default
compiler.cclangccdefault.exe=/usr/bin/clangcc
compiler.cclangccdefault.name=clang default

tools=basil-objdump:basil-readelf:basil:basil-il:basil-dsl:boogie:debug-gts:basil-task-1:basil-task-2:basil-task-3:clangquerydefault:clangtidydefault:readelf:nm:llvmdwarfdumpdefault

tools.basil-objdump.exe=aarch64-unknown-linux-gnu-objdump
tools.basil-objdump.name=objdump (aarch64)
tools.basil-objdump.type=postcompilation
tools.basil-objdump.class=readelf-tool
tools.basil-objdump.stdinHint=disabled

tools.basil-readelf.exe=aarch64-unknown-linux-gnu-readelf
tools.basil-readelf.name=readelf (aarch64)
tools.basil-readelf.exclude=&gcc:&clang
tools.basil-readelf.type=postcompilation
tools.basil-readelf.class=readelf-tool

tools.basil.exe=basil-task
tools.basil.name=BASIL (.bpl output)
tools.basil.exclude=&gcc:&clang
tools.basil.type=postcompilation
tools.basil.options=bpl
tools.basil.languageId=scala
tools.basil.class=readelf-tool

tools.basil-il.exe=basil-task
tools.basil-il.name=BASIL (IL output)
tools.basil-il.exclude=&gcc:&clang
tools.basil-il.type=postcompilation
tools.basil-il.options=il
tools.basil-il.languageId=scala
tools.basil-il.class=readelf-tool

tools.basil-dsl.exe=basil-task
tools.basil-dsl.name=BASIL (DSL output)
tools.basil-dsl.exclude=&gcc:&clang
tools.basil-dsl.type=postcompilation
tools.basil-dsl.options=dsl
tools.basil-dsl.languageId=scala
tools.basil-dsl.class=readelf-tool

tools.boogie.exe=basil-task
tools.boogie.name=BASIL (Boogie verifier)
tools.boogie.exclude=&gcc:&clang
tools.boogie.type=postcompilation
tools.boogie.options=boogie
tools.boogie.class=readelf-tool

tools.debug-gts.exe=basil-task
tools.debug-gts.name=debug-gts
tools.debug-gts.exclude=&gcc:&clang
tools.debug-gts.type=postcompilation
tools.debug-gts.options=debug-gts
tools.debug-gts.languageId=typescript
tools.debug-gts.class=readelf-tool

tools.basil-task-1.exe=basil-task
tools.basil-task-1.name=Generic BASIL task 1
tools.basil-task-1.exclude=&gcc:&clang
tools.basil-task-1.type=postcompilation
tools.basil-task-1.options=
tools.basil-task-1.class=readelf-tool
# tools.basil-task-1.languageId=scala

tools.basil-task-2.exe=basil-task
tools.basil-task-2.name=Generic BASIL task 2
tools.basil-task-2.exclude=&gcc:&clang
tools.basil-task-2.type=postcompilation
tools.basil-task-2.options=
tools.basil-task-2.class=readelf-tool

tools.basil-task-3.exe=basil-task
tools.basil-task-3.name=Generic BASIL task 3
tools.basil-task-3.exclude=&gcc:&clang
tools.basil-task-3.type=postcompilation
tools.basil-task-3.options=
tools.basil-task-3.class=readelf-tool

tools.clangquerydefault.exe=/usr/bin/clang-query
tools.clangquerydefault.name=clang-query (default)
tools.clangquerydefault.type=independent
tools.clangquerydefault.class=clang-query-tool
tools.clangquerydefault.stdinHint=Query commands
tools.clangquerydefault.monacoStdin=true

tools.clangtidydefault.exe=/usr/bin/clang-tidy
tools.clangtidydefault.name=clang-tidy (default)
tools.clangtidydefault.type=independent
tools.clangtidydefault.class=clang-tidy-tool
tools.clangtidydefault.stdinHint=disabled

tools.readelf.name=readelf (default)
tools.readelf.exe=/usr/bin/readelf
tools.readelf.type=postcompilation
tools.readelf.class=readelf-tool
tools.readelf.exclude=djggp
tools.readelf.stdinHint=disabled

tools.nm.name=nm (default)
tools.nm.exe=/usr/bin/nm
tools.nm.type=postcompilation
tools.nm.class=nm-tool
tools.nm.exclude=djggp
tools.nm.stdinHint=disabled

tools.llvmdwarfdumpdefault.exe=/usr/bin/llvm-dwarfdump
tools.llvmdwarfdumpdefault.name=llvm-dwarfdump (default)
tools.llvmdwarfdumpdefault.type=postcompilation
tools.llvmdwarfdumpdefault.class=llvm-dwarfdump-tool
tools.llvmdwarfdumpdefault.stdinHint=disabled
